{% set name = "asciitree" %}
{% set version = "0.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4aa4b9b649f85e3fcb343363d97564aa1fb62e249677f2e18a96765145cc0f6e

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - asciitree
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/mbr/asciitree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Draws ASCII trees.
  description: Draws ASCII trees.
  dev_url: http://github.com/mbr/asciitree
  doc_url: http://github.com/mbr/asciitree

extra:
  recipe-maintainers:
    - kain88-de
    - dotsdl
