travis:
  secure:
    BINSTAR_TOKEN: SS+/5cH5yE6bwAFMYblFLt7phz4r9qwBsGQpWh290XRO5Rw+MvtdgXc9q8CBClaeOvETxyiB5T2QCrdR7FwrHGGoMjYh7RWnwTUinVUnDWAzPDTrZ55GrImLeBSEHJWw6QImzByaFFLYnlw1GUXWUlblpTTo3YfLaqeSWsH+zz914POUnUatjoBXuIEoneUTOCtZCGHlMtPbFDCjYE9ED2ChNd5IGnvxpDnNHxSiXvZfCgK+D02X/3qcc1gwtq8PmE/2xsIqVzpLwkYWQ9o4hGJUUCZ/eL8C8k853bQ9NOqUPIizO6YEpCtpHT8JpooNSB56Ck85hEMWX4eXHIRa8Ea3Q6ag90akTlbm4tobrlZRRAUXBVCQsDGM/nNEwqODxtzaTFLJ5EjoX0w622QheRyUUNDgZOCoWWtFfpjGxyyzq7UoMsilXZZhNxH67sbkD+12QWbaGZQYWiRj0fJMR/B6KmQfo7B2LpQ/E/q1Ph1jwHHHKiLoNIclYqfpu5nA2ZJ+AeNPxN9BMDNWatfxcT05bzCrGBMDjfX8Exu7UqMjZd3XDNqPsNBe998ifEP5EgZbZ0w1NHNXGetydFjNkLcOUDoucaqGvo7hx2HEoyuVV2amuJijJS4v+A0cHwrbCCw3XPsvfG4I34lJ25kkpjdisDa/4Ek8Tpu0F1JjbgA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
