travis:
  secure:
    BINSTAR_TOKEN: YQKx4MGYEcwblNXkSO4vWuCnr8qrITcyVG4sTsXT6HqZKIWIyD8SX6Uhh47Mw3JHArUMK6Rhq5VENMJyOn/kQQH4Ja7qmC0iV+2iO0kWWnXmu7duTKdw49yZV4XhCRpGzq3csi3mGHZkOzIo07gUa+PJRF2jaNLLMP2agLHB3B0BU+LQDA6+i64X29M5lwhW+TsTtyrOg118mb/LaJ14+610bWafYa6IE4uM470dw7RFY35JDJKB5lct4yRWstKpZANWPtEtnpo771XMylEGelUNkv74ZgXbOtEL5QXqpJQEkNJD9H8TKpnedcsL4Cb4pDQWwIcxqBHpMqZXH/wlpZNTKoAwJNnHpDYqXGIMCTGFmnIIhR6Bih0r489mjO2spZGOCYJg85cQVELlXp8CSASe/sm31A7RMGi/SkwEbekClakRVYCoofFkgE6k6+6x1k4uGJPjpXTun0NpLJZxW9T4uTNrkoTjWyooFboKhJP8qrc/Pr5r2eE6fYiBavh3h8ab3qdeS5209QR82G6v56zuZqjJpfm0XgyvfzJ1Q1uDcqck+aELn6eWth1GydC6EAcx6Z0OqDxVALIdw1aOmXD8R+UXGc8no1UQ6wrLoyV7C77/7aUAGp8iGUOB3gEGpEbgRCz12reL1pkbiEM8EXWVleNR61PWiI4W3bfSMQY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
